language: python
python:
  - "2.7"
  - "3.6"
os:
  - linux
addons:
  apt_packages:
    - gfortran
install:
  - conda install libgfortran==1
  - pip install runtests nose
  - pip install .
# command to run tests
script: python runtests.py
