site_name:        gcvspline
repo_url:         https://github.com/charlesll/gcvspline
site_description: A Python interface for the GCVspline FORTRAN library.
site_author:      Charles Le Losq, Yu Feng

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

#extra_css:
#  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

docs_dir: 'docs'

pages:
  - Home: index.md